# Generated by Django 5.1.1 on 2024-09-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo_pokemon', models.CharField(choices=[('Ninguno', 'Ninguno'), ('Normal', 'Normal'), ('Fuego', 'Fuego'), ('Agua', 'Agua'), ('Planta', 'Planta'), ('Eléctrico', 'Eléctrico'), ('Hielo', 'Hielo'), ('Lucha', 'Lucha'), ('Veneno', 'Veneno'), ('Tierra', 'Tierra'), ('Roca', 'Roca'), ('Bicho', 'Bicho'), ('Fantasma', 'Fantasma'), ('Siniestro', 'Siniestro'), ('Acero', 'Acero'), ('Hada', 'Hada'), ('Volador', 'Volador'), ('Psíquico', 'Psíquico'), ('Dragón', 'Dragón'), ('Lucha', 'Lucha'), ('Tierra', 'Tierra')], max_length=50)),
                ('tipo_pokemon2', models.CharField(choices=[('Ninguno', 'Ninguno'), ('Normal', 'Normal'), ('Fuego', 'Fuego'), ('Agua', 'Agua'), ('Planta', 'Planta'), ('Eléctrico', 'Eléctrico'), ('Hielo', 'Hielo'), ('Lucha', 'Lucha'), ('Veneno', 'Veneno'), ('Tierra', 'Tierra'), ('Roca', 'Roca'), ('Bicho', 'Bicho'), ('Fantasma', 'Fantasma'), ('Siniestro', 'Siniestro'), ('Acero', 'Acero'), ('Hada', 'Hada'), ('Volador', 'Volador'), ('Psíquico', 'Psíquico'), ('Dragón', 'Dragón'), ('Lucha', 'Lucha'), ('Tierra', 'Tierra')], max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=50)),
            ],
        ),
    ]
